//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWebCSharp.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebService3Soap")]
    public interface WebService3Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Listar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Listar", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] AgregarAlumno(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] EliminarAlumno(string CodAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string CodAlumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] ActualizarAlumno(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarAlumno(string texto, string criterio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService3SoapChannel : ClienteWebCSharp.ServiceReference3.WebService3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<ClienteWebCSharp.ServiceReference3.WebService3Soap>, ClienteWebCSharp.ServiceReference3.WebService3Soap {
        
        public WebService3SoapClient() {
        }
        
        public WebService3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Listar() {
            return base.Channel.Listar();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListarAsync() {
            return base.Channel.ListarAsync();
        }
        
        public string[] AgregarAlumno(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.AgregarAlumno(CodAlumno, Apellido, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> AgregarAlumnoAsync(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.AgregarAlumnoAsync(CodAlumno, Apellido, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public string[] EliminarAlumno(string CodAlumno) {
            return base.Channel.EliminarAlumno(CodAlumno);
        }
        
        public System.Threading.Tasks.Task<string[]> EliminarAlumnoAsync(string CodAlumno) {
            return base.Channel.EliminarAlumnoAsync(CodAlumno);
        }
        
        public string[] ActualizarAlumno(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.ActualizarAlumno(CodAlumno, Apellido, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public System.Threading.Tasks.Task<string[]> ActualizarAlumnoAsync(string CodAlumno, string Apellido, string Nombres, string LugarNac, string FechaNac, string CodEscuela) {
            return base.Channel.ActualizarAlumnoAsync(CodAlumno, Apellido, Nombres, LugarNac, FechaNac, CodEscuela);
        }
        
        public System.Data.DataSet BuscarAlumno(string texto, string criterio) {
            return base.Channel.BuscarAlumno(texto, criterio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarAlumnoAsync(string texto, string criterio) {
            return base.Channel.BuscarAlumnoAsync(texto, criterio);
        }
    }
}
